version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - NAME=${NAME}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    env_file:
      - .env
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
volumes:
  postgres_data: