version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    env_file:
      - .env
  app:
    build: .
    command: sh -c "sleep 10 && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
volumes:
  postgres_data: