# Generated by Django 5.1.7 on 2025-03-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadberry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='price',
            field=models.FloatField(default=2, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
