# Generated by Django 5.1.7 on 2025-03-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadberry', '0002_position_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
    ]
