# Generated by Django 5.1.7 on 2025-03-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadberry', '0003_position_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='breadberry.category', verbose_name='Категория'),
        ),
    ]
